- name: "Setup Node Exporter"
  vars_files:
    - vars/prod.yml
  gather_facts: no
  hosts: kamatera
  remote_user: "{{remote_admin}}"
  become: true
  become_method: sudo
  tasks:
    - name: "Creating user {{app_name}}"
      user:
        name: "{{app_name}}"
        shell: /bin/false
        system: true
        password: "{{user_password | password_hash('sha512') }}"
        state: present

    - name: "Create app folder /usr/local/{{app_name}}"
      file:
        path: "/usr/local/{{app_name}}"
        state: directory
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0700'

    - name: Download node exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.11.1/node_exporter-1.11.1.linux-amd64.tar.gz
        dest: "/usr/local/{{app_name}}"
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0440'
        validate_certs: true

    - name: Unzip archive
      unarchive:
        remote_src: yes
        src: "/usr/local/{{app_name}}/node_exporter-1.11.1.linux-amd64.tar.gz"
        dest: "/usr/local/{{app_name}}"
        owner: "{{app_name}}"
        group: "{{app_name}}"
        extra_opts: ['--strip-components=1', '--show-stored-names']

    - name: "Create app folder /etc/{{app_name}}"
      file:
        path: "/etc/{{app_name}}"
        state: directory
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0700'

#    - name: "Upload local config file"
#      copy:
#        src: "data/config.yml"
#        dest: "/etc/{{app_name}}/"
#        owner: "{{app_name}}"
#        group: "{{app_name}}"
#        mode: '0700'

    - name: "Copy ssl certificate for {{app_name}}"
      copy:
        remote_src: true
        src: /etc/letsencrypt/live/113-30-190-16.cloud-xip.com/fullchain.pem
        dest: "/etc/{{app_name}}/"
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0700'

    - name: "Copy ssl private key for {{app_name}}"
      copy:
        remote_src: true
        src: /etc/letsencrypt/live/113-30-190-16.cloud-xip.com/privkey.pem
        dest: "/etc/{{app_name}}/"
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0700'

    - name: "Render web config file to /etc/{{app_name}}/web-config.yml"
      template:
        src: data/web-config-template.yml
        dest: "/etc/{{app_name}}/web-config.yml"
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0700'

    - name: "Render systemd service-template.service config file to /etc/systemd/system/{{app_name}}.service"
      template:
        src: data/service-template.service
        dest: "/etc/systemd/system/{{app_name}}.service"
        owner: root
        group: root

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: "Start service {{app_name}}"
      systemd:
        name: "{{app_name}}"
        state: started
        enabled: true