- name: "Setup Prometheus"
  vars_files:
    - vars/prod.yml
  gather_facts: no
  hosts: kamatera
  remote_user: "{{remote_admin}}"
  become: true
  become_method: sudo
  tasks:
    - name: "Upload local config file"
      copy:
        src: "data/prometheus.yml"
        dest: "/etc/{{app_name}}/"
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0700'

    - name: "Copy ssl certificate for {{app_name}}"
      copy:
        remote_src: true
        src: /etc/letsencrypt/live/113-30-190-16.cloud-xip.com/fullchain.pem
        dest: "/etc/{{app_name}}/"
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0700'

    - name: "Copy ssl private key for {{app_name}}"
      copy:
        remote_src: true
        src: /etc/letsencrypt/live/113-30-190-16.cloud-xip.com/privkey.pem
        dest: "/etc/{{app_name}}/"
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0700'

    - name: "Restart service {{app_name}}"
      systemd:
        name: "{{app_name}}"
        state: restarted
        enabled: true