- name: "Setup Blackbox SSL Autoupdater"
  vars_files:
    - vars/prod.yml
  gather_facts: no
  hosts: castle
  remote_user: "{{remote_admin}}"
  become: true
  become_method: sudo
  tasks:
    - name: "Create script folder /opt/{{app_name}}/scripts"
      file:
        path: "/opt/{{app_name}}/scripts"
        state: directory
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0700'

    - name: "Render local script file ssl-updater.sh to /opt/{{app_name}}/scripts/"
      template:
        src: data/ssl-updater.sh
        dest: "/opt/{{app_name}}/scripts/ssl-updater.sh"
        owner: "{{app_name}}"
        group: "{{app_name}}"
        mode: '0500'

    - name: Copy systemd devops-blackbox-ssl-updater.service file to /etc/systemd/system/
      copy:
        src: data/devops-blackbox-ssl-updater.service
        dest: /etc/systemd/system/
        owner: root
        group: root

    - name: Copy systemd devops-blackbox-ssl-updater.timer file to /etc/systemd/system/
      copy:
        src: data/devops-blackbox-ssl-updater.timer
        dest: /etc/systemd/system/
        owner: root
        group: root

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start timer
      systemd:
        name: devops-blackbox-ssl-updater.timer
        state: started
        enabled: true